-- vim api reference https://neovim.io/doc/user/api.html#nvim_get_keymap()

require('plugins')
require('mason-config')
require('lsp-config')
require('code-completion')
require('nvimtree-config')
require('styling')
require('custom-settings')
require('vim-floaterm')
require('execution-commands')
require('telescope-config')
require('rust-tools-config')
require('nvim-treesitter-config')
