vim.cmd[[colorscheme dracula]]
vim.cmd[[highlight Normal ctermbg=none]]
vim.cmd[[highlight NonText ctermbg=none]]
vim.cmd[[highlight Normal guibg=none]]
vim.cmd[[highlight NonText guibg=none]]
vim.cmd[[highlight NvimTreeNormal guibg=none]]
vim.cmd[[highlight NvimtreeNormal guibg=none]]
